hasPermission(RHO,GOAL) :- hasObligation(RHO,GOAL).
violationCondition(AGENT,GOAL,CONDITION):- hasCondition(GOAL,CONDITIONSET),notIsPresent(CONDITION),isElementOf(CONDITION,CONDTIONSET),tryReach(AGENT,GOAL).
violationRelation(AGENT,GOAL,RELATION):- hasRelation(GOAL,RELATIONSET),notIsPresent(RELATION),isElementOf(RELATION,RELATIONSET),tryReach(AGENT,GOAL).
violationEntity(AGENT,GOAL,ENTITY) :- hasEntity(GOAL,ENTITYSET),notIsPresent(ENTITY),isElementOf(ENTITY,ENTITYSUBSET),tryReach(AGENT,GOAL).
consequenceOfBadEvent(GOAL,AGENT,RISK,FATALITY) :- violationCondition(AGENT,GOAL,CONDITION),hasRisk(CONDITION,RISK,FATALITY).
consequenceOfBadEvent(GOAL,AGENT,RISK,FATALITY) :- violationRelation(AGENT,GOAL,RISK),hasRisk(CONDITION,RISK,FATALITY).
hasPossibility(OTHERRELATION) :- violationRelation(AGENT,GOAL,RISK),affects(RELATION,OTHERRELATION),notHasPossibility(RELATION).
stopIn(GOAL):-violationEntity(AGENT,GOAL,ENTITY).
consequenceOfBadEvent(GOAL,AGENT,RISK,FATALITY) :- hasRelation(GOAL,RELATIONSET),isElementOf(RELATION,RELATIONSET),hasRisk(RELATION,RISK,FATALITY),tryReach(AGENT,GOAL).
stopIn(GOAL) :- consequenceOfBadEvent(GOAL,AGENT,RISK,FATALITY).
isReached(GOAL) :- notStopIn(GOAL,AGENTDONETHIS),isSubSet(AGENTDONETHIS,AGENTOBLIGATIOTHIS).

hasRisk(umidadesetenta,eletrocutado,morte).
hasRisk(novento,eletrocutado,morte).
hasRisk(nochuva,eletrocutado,morte).
hasRisk(sol,eletrocutado,morte).

relationHas(relationagente1capacete,agente1,capacete).
relationHas(relationagente2capacete,agente2,capacete).
relationHas(relationagente3capacete,agente3,capacete).
relationHas(relationagente4capacete,agente4,capacete).
relationHas(relationagente5capacete,agente5,capacete).
relationHas(relationagente6capacete,agente6,capacete).
relationHas(relationagente7capacete,agente7,capacete).
relationHas(relationagente1oculos,agente1,oculos).
relationHas(relationagente2oculos,agente2,oculos).
relationHas(relationagente3oculos,agente3,oculos).
relationHas(relationagente4oculos,agente4,oculos).
relationHas(relationagente5oculos,agente5,oculos).
relationHas(relationagente6oculos,agente6,oculos).
relationHas(relationagente7oculos,agente7,oculos).
relationHas(relationagente1roupagem,agente1,roupagem).
relationHas(relationagente2roupagem,agente2,roupagem).
relationHas(relationagente3roupagem,agente3,roupagem).
relationHas(relationagente4roupagem,agente4,roupagem).
relationHas(relationagente5roupagem,agente5,roupagem).
relationHas(relationagente6roupagem,agente6,roupagem).
relationHas(relationagente7roupagem,agente7,roupagem).
relationHas(relationagente1luva,agente1,luva).
relationHas(relationagente2luva,agente2,luva).
relationHas(relationagente3luva,agente3,luva).
relationHas(relationagente4luva,agente4,luva).
relationHas(relationagente5luva,agente5,luva).
relationHas(relationagente6luva,agente6,luva).
relationHas(relationagente7luva,agente7,luva).
relationHas(relationagente1bota,agente1,bota).
relationHas(relationagente2bota,agente2,bota).
relationHas(relationagente3bota,agente3,bota).
relationHas(relationagente4bota,agente4,bota).
relationHas(relationagente5bota,agente5,bota).
relationHas(relationagente6bota,agente6,bota).
relationHas(relationagente7bota,agente7,bota).
relationHas(relationagente1pano,agente1,pano).
relationHas(relationagente2pano,agente2,pano).
relationHas(relationagente3pano,agente3,pano).
relationHas(relationagente4pano,agente4,pano).
relationHas(relationagente5pano,agente5,pano).
relationHas(relationagente6pano,agente6,pano).
relationHas(relationagente7pano,agente7,pano).
relationHas(relationpanoglicerina,pano,glicerina).
relationHas(relationpanocorda,pano,corda).
relationHas(relationpanobastaouniversal,pano,bastaouniversal).
relationHas(relationpanosoquete,pano,soquete).
relationHas(relationbastaogarra,pano,bastaogarra).
relationHas(relationagente1sela,agente1,sela).
relationHas(relationagente2sela,agente2,sela).
relationHas(relationagente3sela,agente3,sela).
relationHas(relationagente4sela,agente4,sela).
relationHas(relationagente5sela,agente5,sela).
relationHas(relationagente6sela,agente6,sela).
relationHas(relationagente7sela,agente7,sela).
relationHas(relationagente1colar,agente1,colar).
relationHas(relationagente2colar,agente2,colar).
relationHas(relationagente3colar,agente3,colar).
relationHas(relationagente4colar,agente4,colar).
relationHas(relationagente5colar,agente5,colar).
relationHas(relationagente6colar,agente6,colar).
relationHas(relationagente7colar,agente7,colar).
relationHas(relationagente1bastaogarra,agente1,bastaogarra).
relationHas(relationagente2bastaogarra,agente2,bastaogarra).
relationHas(relationagente3bastaogarra,agente3,bastaogarra).
relationHas(relationagente4bastaogarra,agente4,bastaogarra).
relationHas(relationagente5bastaogarra,agente5,bastaogarra).
relationHas(relationagente6bastaogarra,agente6,bastaogarra).
relationHas(relationagente7bastaogarra,agente7,bastaogarra).
relationHas(relationtorresela,torre,sela).
relationHas(relationselacolar,sela,colar).
relationHas(relationcolarbastaogarra,colar,bastaogarra).
relationHas(relationagente1bastaouniversal,agente1,bastaouniversal).
relationHas(relationagente2bastaouniversal,agente2,bastaouniversal).
relationHas(relationagente3bastaouniversal,agente3,bastaouniversal).
relationHas(relationagente4bastaouniversal,agente4,bastaouniversal).
relationHas(relationagente5bastaouniversal,agente5,bastaouniversal).
relationHas(relationagente6bastaouniversal,agente6,bastaouniversal).
relationHas(relationagente7bastaouniversal,agente7,bastaouniversal).
relationHas(relationcordabastaouniversal,corda,bastaouniversal).
relationHas(relationcordacarretilha,corda,carretilha).
relationHas(relationbastaouniversalcarretilha,bastaouniversal,carretilha).
relationHas(relationbastaouniversalcolar,bastaouniversal,colar).
relationHas(relationbastaouniversalestopo,bastaouniversal,estopo).
relationHas(relationcordaestopo,corda,estopo).
relationHas(relationestopoisoladorvelho,estopo,isoladorvelho).
relationHas(relationagente1chavecatraca,agente1,chavecatraca).
relationHas(relationagente2chavecatraca,agente2,chavecatraca).
relationHas(relationagente3chavecatraca,agente3,chavecatraca).
relationHas(relationagente4chavecatraca,agente4,chavecatraca).
relationHas(relationagente5chavecatraca,agente5,chavecatraca).
relationHas(relationagente6chavecatraca,agente6,chavecatraca).
relationHas(relationagente7chavecatraca,agente7,chavecatraca).
relationHas(relationchavecatracabastaouniversal,chavecatraca,bastaouniversal).
relationHas(relationchavecatracaparafuso,chavecatraca,parafuso).
relationHas(relationparafusoconector,parafuso,conector).
relationHas(relationagente1bastaosoquete,agente1,bastaosoquete).
relationHas(relationagente2bastaosoquete,agente2,bastaosoquete).
relationHas(relationagente3bastaosoquete,agente3,bastaosoquete).
relationHas(relationagente4bastaosoquete,agente4,bastaosoquete).
relationHas(relationagente5bastaosoquete,agente5,bastaosoquete).
relationHas(relationagente6bastaosoquete,agente6,bastaosoquete).
relationHas(relationagente7bastaosoquete,agente7,bastaosoquete).
relationHas(relationbastaosoqueteparafuso,bastaosoquete,parafuso).
relationHas(relationagente1corda,agente1,corda).
relationHas(relationagente2corda,agente2,corda).
relationHas(relationagente3corda,agente3,corda).
relationHas(relationagente4corda,agente4,corda).
relationHas(relationagente5corda,agente5,corda).
relationHas(relationagente6corda,agente6,corda).
relationHas(relationagente7corda,agente7,corda).
relationHas(relationagente1isoladorvelho,agente1,isoladorvelho).
relationHas(relationagente2isoladorvelho,agente2,isoladorvelho).
relationHas(relationagente3isoladorvelho,agente3,isoladorvelho).
relationHas(relationagente4isoladorvelho,agente4,isoladorvelho).
relationHas(relationagente5isoladorvelho,agente5,isoladorvelho).
relationHas(relationagente6isoladorvelho,agente6,isoladorvelho).
relationHas(relationagente7isoladorvelho,agente7,isoladorvelho).
relationHas(relationagente1isoladornovo,agente1,isoladornovo).
relationHas(relationagente2isoladornovo,agente2,isoladornovo).
relationHas(relationagente3isoladornovo,agente3,isoladornovo).
relationHas(relationagente4isoladornovo,agente4,isoladornovo).
relationHas(relationagente5isoladornovo,agente5,isoladornovo).
relationHas(relationagente6isoladornovo,agente6,isoladornovo).
relationHas(relationagente7isoladornovo,agente7,isoladornovo).
relationHas(relationcordabastaogarra,corda,bastaogarra).
relationHas(relationbastaogarrasela,bastaogarra,sela).
relationHas(relationagente1carretilha,agente1,carretilha).
relationHas(relationagente2carretilha,agente2,carretilha).
relationHas(relationagente3carretilha,agente3,carretilha).
relationHas(relationagente4carretilha,agente4,carretilha).
relationHas(relationagente5carretilha,agente5,carretilha).
relationHas(relationagente6carretilha,agente6,carretilha).
relationHas(relationagente7carretilha,agente7,carretilha).
relationHas(relationbastaouniversalcorda,bastaouniversal,corda).
relationHas(relationbastaouniversaltorre,bastaouniversal,torre).
relationHas(relationestopocorda,estopo,corda).
relationHas(relationestopoisoladornovo,estopo,isoladornovo).
relationHas(relationbastaouniversalsela,bastaouniversal,sela).
relationHas(relationbastaogarratorre,bastaogarra,torre).
relationHas(relationbastaogarracondutor,bastaogarra,condutor).
relationHas(relationbastaouniversalestopo,bastaouniversal,estopo).
relationHas(relationagente1colar,agente1,colar).
relationHas(relationagente2colar,agente2,colar).
relationHas(relationagente3colar,agente3,colar).
relationHas(relationagente4colar,agente4,colar).
relationHas(relationagente5colar,agente5,colar).
relationHas(relationagente6colar,agente6,colar).
relationHas(relationagente7colar,agente7,colar).
relationHas(relationparafusotorre,parafuso,torre).
relationHas(relationcondutivimetrocorda,condutivimetro,corda).
relationHas(relationcondutivimetrobastaouniversal,condutivimetro,bastaouniversal).
relationHas(relationcondutivimetrobastaogarra,condutivimetro,bastaogarra).
relationHas(relationcondutivimetrosoquete,condutivimetro,soquete).

affects(relationagente1capacete,relationbastaogarracondutor).
affects(relationagente2capacete,relationbastaogarracondutor).
affects(relationagente3capacete,relationbastaogarracondutor).
affects(relationagente4capacete,relationbastaogarracondutor).
affects(relationagente5capacete,relationbastaogarracondutor).
affects(relationagente6capacete,relationbastaogarracondutor).
affects(relationagente7capacete,relationbastaogarracondutor).
affects(relationagente1capacete,relationcordaestopo).
affects(relationagente2capacete,relationcordaestopo).
affects(relationagente3capacete,relationcordaestopo).
affects(relationagente4capacete,relationcordaestopo).
affects(relationagente5capacete,relationcordaestopo).
affects(relationagente6capacete,relationcordaestopo).
affects(relationagente7capacete,relationcordaestopo).
affects(relationagente1capacete,relationchavecatracaparafuso).
affects(relationagente2capacete,relationchavecatracaparafuso).
affects(relationagente3capacete,relationchavecatracaparafuso).
affects(relationagente4capacete,relationchavecatracaparafuso).
affects(relationagente5capacete,relationchavecatracaparafuso).
affects(relationagente6capacete,relationchavecatracaparafuso).
affects(relationagente7capacete,relationchavecatracaparafuso).
affects(relationagente1capacete,relationparafusoconector).
affects(relationagente2capacete,relationparafusoconector).
affects(relationagente3capacete,relationparafusoconector).
affects(relationagente4capacete,relationparafusoconector).
affects(relationagente5capacete,relationparafusoconector).
affects(relationagente6capacete,relationparafusoconector).
affects(relationagente7capacete,relationparafusoconector).
affects(relationagente1capacete,relationsoqueteparafuso).
affects(relationagente2capacete,relationsoqueteparafuso).
affects(relationagente3capacete,relationsoqueteparafuso).
affects(relationagente4capacete,relationsoqueteparafuso).
affects(relationagente5capacete,relationsoqueteparafuso).
affects(relationagente6capacete,relationsoqueteparafuso).
affects(relationagente7capacete,relationsoqueteparafuso).
affects(relationagente1capacete,relationagente1corda).
affects(relationagente2capacete,relationagente1corda).
affects(relationagente3capacete,relationagente1corda).
affects(relationagente4capacete,relationagente1corda).
affects(relationagente5capacete,relationagente1corda).
affects(relationagente6capacete,relationagente1corda).
affects(relationagente7capacete,relationagente1corda).
affects(relationagente1capacete,relationagente2corda).
affects(relationagente2capacete,relationagente2corda).
affects(relationagente3capacete,relationagente2corda).
affects(relationagente4capacete,relationagente2corda).
affects(relationagente5capacete,relationagente2corda).
affects(relationagente6capacete,relationagente2corda).
affects(relationagente7capacete,relationagente2corda).
affects(relationagente1capacete,relationagente3corda).
affects(relationagente2capacete,relationagente3corda).
affects(relationagente3capacete,relationagente3corda).
affects(relationagente4capacete,relationagente3corda).
affects(relationagente5capacete,relationagente3corda).
affects(relationagente6capacete,relationagente3corda).
affects(relationagente7capacete,relationagente3corda).
affects(relationagente1capacete,relationagente4corda).
affects(relationagente2capacete,relationagente4corda).
affects(relationagente3capacete,relationagente4corda).
affects(relationagente4capacete,relationagente4corda).
affects(relationagente5capacete,relationagente4corda).
affects(relationagente6capacete,relationagente4corda).
affects(relationagente7capacete,relationagente4corda).
affects(relationagente1capacete,relationagente5corda).
affects(relationagente2capacete,relationagente5corda).
affects(relationagente3capacete,relationagente5corda).
affects(relationagente4capacete,relationagente5corda).
affects(relationagente5capacete,relationagente5corda).
affects(relationagente6capacete,relationagente5corda).
affects(relationagente7capacete,relationagente5corda).
affects(relationagente1capacete,relationagente6corda).
affects(relationagente2capacete,relationagente6corda).
affects(relationagente3capacete,relationagente6corda).
affects(relationagente4capacete,relationagente6corda).
affects(relationagente5capacete,relationagente6corda).
affects(relationagente6capacete,relationagente6corda).
affects(relationagente7capacete,relationagente6corda).
affects(relationagente1capacete,relationagente7corda).
affects(relationagente2capacete,relationagente7corda).
affects(relationagente3capacete,relationagente7corda).
affects(relationagente4capacete,relationagente7corda).
affects(relationagente5capacete,relationagente7corda).
affects(relationagente6capacete,relationagente7corda).
affects(relationagente7capacete,relationagente7corda).
